### ISSUE TITLE
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!....So Lost!

### ISSUE THREAD

**Issue by lbedrosian** [learn-co-curriculum/phase-0-macos-env-ruby#5]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/4327/pages/installing-ruby-on-macos?module_item_id=251501

## Describe the bug

Was suppose to run $ 'rvm install 2.7.4 --default' and it keeps giving me an error, I've tried troubleshooting and I can not get an answer. I get an error following that command that says 'Searching for binary rubies, this might take some time.
No binary rubies available for: osx/11.5/x86_64/ruby-2.7.4.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
Requirements installation failed with status: 1.'

## What is the expected behavior?

I was to run 'rvm list' and then get a message starting with "=* ruby-2.7.4"
## Screenshots
![Screenshot 2021-07-25 at 3 07 53 PM](https://user-images.githubusercontent.com/76708774/126910472-6b4610dc-9995-40a1-94d4-bb6ad8a409ae.png)

## What OS are you using?

- [X] OS X (Macbook Air 2020 M1 chip)
- [ ] WSL
- [ ] Linux

## Any additional context?

Spent many hours on this. I went ahead cause it says I have ruby 3.0.0 and thought I could get away with it. The first CSS assignment won't let me bundle cause it says I need ruby 2.0

**Comment by ihollander** [comment]
Hi @lbedrosian - sorry to hear you ran into this issue! Based on your description, it sounds like the issue may be related to your environment setup rather than with the lesson itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

To get help with your question, you should either: 

- Reach out to your instructor (if you've started the program and have an instructor)
- Use the [#js-prework-support](https://flatiron-school.slack.com/archives/C01KEEVJU3Y) Slack channel (if you're working on the prework)

Please re-open this issue if you believe the lesson needs to be updated, and if you have suggestions for additional instructions related to this issue that may help future students.

Hope you are able to get this resolved!
